create table course (begin_date date, begin_shift integer, day_of_week integer, end_date date, end_shift integer, registered_number integer, total_number integer, week_distance integer, course_id varchar(255), id varchar(255) not null, language varchar(255), lecturer_name varchar(255), main_course_id varchar(255), room varchar(255), semester_id varchar(255), subject_id varchar(255), primary key (id)) engine=InnoDB;
create table registration (course_id varchar(255) not null, student_id varchar(255) not null, primary key (course_id, student_id)) engine=InnoDB;
create table registration_period (close_time datetime(6), open_time datetime(6), id varchar(255) not null, semester_id varchar(255), primary key (id)) engine=InnoDB;
create table semester (semester_num integer, year integer, id varchar(255) not null, primary key (id)) engine=InnoDB;
create table student (admission_year integer, falcuty_name varchar(255) not null, id varchar(255) not null, program varchar(255) not null, user_id varchar(255) not null, primary key (id)) engine=InnoDB;
create table subject (practice_credit_number integer, theory_credit_number integer, id varchar(255) not null, name varchar(255), primary key (id)) engine=InnoDB;
create table subject_relation (type tinyint check (type between 0 and 1), curr_subject_id varchar(255) not null, pre_subject_id varchar(255) not null, primary key (curr_subject_id, pre_subject_id)) engine=InnoDB;
create table user (email varchar(255) not null, id varchar(255) not null, name varchar(255), password varchar(255) not null, role enum ('ADMIN','STUDENT'), primary key (id)) engine=InnoDB;
alter table course add constraint UKtckrkcy5xdlahye20nppf6i1l unique (course_id);
alter table student add constraint UKbkix9btnoi1n917ll7bplkvg5 unique (user_id);
alter table subject add constraint UKp1jgir6qcpmqnxt4a8105wsot unique (name);
alter table user add constraint UKob8kqyqqgmefl0aco34akdtpe unique (email);
alter table user add constraint UKkiqfjabx9puw3p1eg7kily8kg unique (password);
alter table course add constraint FKmbr38vd0ju01t2oqerncstlph foreign key (main_course_id) references course (id);
alter table course add constraint FKlmyb73uymsfhqh374ndr3n4c0 foreign key (semester_id) references semester (id);
alter table course add constraint FKm1expnaas0onmafqpktmjixnx foreign key (subject_id) references subject (id);
alter table registration add constraint FKo0ifq05dge7ssg2voqs6wtik6 foreign key (course_id) references course (id);
alter table registration add constraint FKcxvegulu1x4mjcvy3116tu5xu foreign key (student_id) references student (id);
alter table registration_period add constraint FKb02antaqgp5wrtq71yvh3d2mh foreign key (semester_id) references semester (id);
alter table student add constraint FKk5m148xqefonqw7bgnpm0snwj foreign key (user_id) references user (id);
alter table subject_relation add constraint FKogjeox0uf7yoijpqr8gmtexil foreign key (curr_subject_id) references subject (id);
alter table subject_relation add constraint FK3l6b64f8qg6bp18j2k3c37e1f foreign key (pre_subject_id) references subject (id);
