spring.application.name=dkhp_backend
server.servlet.context-path=/api

# MySQL DB Config
spring.datasource.url=jdbc:mysql://localhost:3307/dkhpdb
spring.datasource.username=root
spring.datasource.password=MyNewPass123!
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.javax.persistence.schema-generation.scripts.action=update
spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=schema.sql
spring.jpa.properties.javax.persistence.schema-generation.create-source=metadata
spring.jpa.show-sql=true

# CORS Config
cors.origins=http://localhost:3000

# Swagger Config
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.default-produces-media-type=application/json


# Jwt Config
jwt.header=Authorization
jwt.secret=asdcghcuchdurugthahsdngytieoshgynwbeydyenddcykasdcghcuchdurugthahsdngytieoshgynwbethahsdngytieoshgynwbe
jwt.prefix=Bearer 
jwt.access-token-expiration=3600
jwt.refresh-token-expiration=18000
jwt.temp-password-token-expiration=300

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tienhung17092004@gmail.com
spring.mail.password=m h o m p y h b j t m a h d b k
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
mail.from-address=CourseRegistration

# OTP Config
otp.expiration=5