create table admin (id varchar(255) not null, name varchar(255), role tinyint not null check (role between 0 and 1), user_id varchar(255) not null, primary key (id)) engine=InnoDB;
create table course (id varchar(255) not null, begin_date date, begin_shift integer, day_of_week integer, end_date date, end_shift integer, language tinyint check (language between 0 and 1), lecturer_name varchar(255), registered_number integer, room varchar(255), total_number integer, week_distance integer, main_course_id varchar(255), semester_id varchar(255), subject_id varchar(255), primary key (id)) engine=InnoDB;
create table registration (course_id varchar(255) not null, student_id varchar(255) not null, primary key (course_id, student_id)) engine=InnoDB;
create table registration_period (id varchar(255) not null, close_time datetime(6), open_time datetime(6), semester_id varchar(255), primary key (id)) engine=InnoDB;
create table semester (id varchar(255) not null, semester_num integer, year integer, primary key (id)) engine=InnoDB;
create table student (id varchar(255) not null, admission_year integer, falcuty_name varchar(255) not null, program varchar(255) not null, user_id varchar(255) not null, primary key (id)) engine=InnoDB;
create table subject (id varchar(255) not null, name varchar(255), practice_credit_number integer, theory_credit_number integer, primary key (id)) engine=InnoDB;
create table subject_relation (type tinyint check (type between 0 and 1), pre_subject_id varchar(255) not null, curr_subject_id varchar(255) not null, primary key (curr_subject_id, pre_subject_id)) engine=InnoDB;
create table user (id varchar(255) not null, email varchar(255) not null, is_actived bit, is_blocked bit, otp_code varchar(255), otp_time datetime(6), password varchar(255), role enum ('ADMIN','STUDENT') not null, primary key (id)) engine=InnoDB;

alter table admin add constraint UKhawikyhwwfvbnog5byokutpff unique (user_id);
alter table student add constraint UKbkix9btnoi1n917ll7bplkvg5 unique (user_id);
alter table user add constraint UKob8kqyqqgmefl0aco34akdtpe unique (email);
alter table admin add constraint FK8ahhk8vqegfrt6pd1p9i03aej foreign key (user_id) references user (id);
alter table course add constraint FKmbr38vd0ju01t2oqerncstlph foreign key (main_course_id) references course (id);
alter table course add constraint FKlmyb73uymsfhqh374ndr3n4c0 foreign key (semester_id) references semester (id);
alter table course add constraint FKm1expnaas0onmafqpktmjixnx foreign key (subject_id) references subject (id);
alter table registration add constraint FKo0ifq05dge7ssg2voqs6wtik6 foreign key (course_id) references course (id);
alter table registration add constraint FKcxvegulu1x4mjcvy3116tu5xu foreign key (student_id) references student (id);
alter table registration_period add constraint FKb02antaqgp5wrtq71yvh3d2mh foreign key (semester_id) references semester (id);
alter table student add constraint FKk5m148xqefonqw7bgnpm0snwj foreign key (user_id) references user (id);
alter table subject_relation add constraint FKogjeox0uf7yoijpqr8gmtexil foreign key (curr_subject_id) references subject (id);
alter table subject_relation add constraint FK3l6b64f8qg6bp18j2k3c37e1f foreign key (pre_subject_id) references subject (id);